"use client";
import { useMemo, useState } from "react";
import type { Diagnostic } from "../lib/diagnostics";
import { calculateFinancialMetrics } from "../lib/financial-metrics";
import { FinancialDetail } from "./FinancialDetail";
import type { ConsultantConfig } from "../lib/consultant-config";

const money=(cents:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format((cents||0)/100);
const percent=(value:number,base:number)=>base?value/base*100:0;
const pct=(value:number)=>`${value.toFixed(1).replace(".",",")}%`;
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value));
const initials=(name:string)=>name.split(" ").slice(0,2).map((part)=>part[0]).join("").toUpperCase();

function metrics(d:Diagnostic){
  const m=calculateFinancialMetrics(d);
  return{...m,net:m.netRevenue,gross:m.grossResult,operating:m.operatingResult,financial:0};
}

function Status({value}:{value:number}){return <span className={`status ${value>=0?"positive":"negative"}`}><i/>{value>=0?"Lucro":"Prejuízo"}</span>}
function Health({label,value,good,warn}:{label:string;value:number;good:number;warn:number}){const level=value<=good?"good":value<=warn?"warn":"bad";return <div className="health-row"><span><i className={level}/>{label}</span><strong>{pct(value)}</strong><small>{level==="good"?"Saudável":level==="warn"?"Atenção":"Crítico"}</small></div>}

export function Dashboard({initialDiagnostics,source,loadError,consultant}:{initialDiagnostics:Diagnostic[];source:string;loadError?:string;consultant:ConsultantConfig}){
  const [selected,setSelected]=useState<Diagnostic|null>(null),[query,setQuery]=useState(""),[range,setRange]=useState("todas"),[status,setStatus]=useState("todos");
  const rows=useMemo(()=>initialDiagnostics.filter((d)=>{
    const result=metrics(d).operating; const text=`${d.empresa_nome} ${d.nome}`.toLowerCase();
    return text.includes(query.toLowerCase())&&(range==="todas"||d.faturamento===range)&&(status==="todos"||(status==="lucro"?result>=0:result<0));
  }).sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at)),[initialDiagnostics,query,range,status]);
  if(selected)return <FinancialDetail diagnostic={selected} consultant={consultant} onBack={()=>setSelected(null)}/>;
  const profitable=initialDiagnostics.filter((d)=>metrics(d).operating>=0).length;
  return <main className="app-shell"><Sidebar/><section className="workspace">
    <header className="topbar"><div><span className="eyebrow">Visão geral</span><h1>Diagnósticos financeiros</h1><p>Acompanhe e analise a saúde financeira de cada empresa.</p></div><div className="user-menu"><span className="avatar">CB</span><div><strong>Cristian Barbosa</strong><small>Consultor financeiro</small></div><form action="/api/logout" method="post"><button title="Sair">↗</button></form></div></header>
    <div className="sync-line"><span className="sync-dot"/> {source}<span>•</span><span>{initialDiagnostics.length} registros</span></div>
    {loadError&&<div className="config-alert"><strong>Conexão pendente</strong><span>{loadError} Configure a conta de serviço para liberar os dados.</span></div>}
    <section className="summary-grid"><article><span>Total de diagnósticos</span><strong>{initialDiagnostics.length}</strong><small>Formulários recebidos</small></article><article><span>Empresas com lucro</span><strong>{profitable}</strong><small>{initialDiagnostics.length?pct(profitable/initialDiagnostics.length*100):"0%"} da base</small></article><article><span>Empresas em atenção</span><strong>{initialDiagnostics.length-profitable}</strong><small>Resultado operacional negativo</small></article></section>
    <section className="list-card"><div className="list-head"><div><h2>Empresas</h2><p>Selecione um diagnóstico para abrir a análise completa.</p></div><div className="filters"><label className="search"><span>⌕</span><input aria-label="Buscar empresa ou responsável" placeholder="Buscar empresa ou responsável" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select aria-label="Faixa de faturamento" value={range} onChange={(e)=>setRange(e.target.value)}><option value="todas">Todas as faixas</option>{[...new Set(initialDiagnostics.map(d=>d.faturamento))].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Status" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="todos">Todos os status</option><option value="lucro">Lucro</option><option value="prejuizo">Prejuízo</option></select></div></div>
      <div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Responsável</th><th>Preenchimento</th><th>Faturamento mensal</th><th>Situação</th><th/></tr></thead><tbody>{rows.map((d)=>{const m=metrics(d);return <tr key={d.id} onClick={()=>setSelected(d)} tabIndex={0} onKeyDown={(e)=>e.key==="Enter"&&setSelected(d)}><td><div className="company"><span>{initials(d.empresa_nome)}</span><div><strong>{d.empresa_nome}</strong><small>{d.atividade}</small></div></div></td><td><strong>{d.nome}</strong><small>{d.cidade}</small></td><td>{date(d.created_at)}</td><td><strong>{money(d.dre_faturamento)}</strong></td><td><Status value={m.operating}/></td><td><button aria-label={`Abrir ${d.empresa_nome}`}>→</button></td></tr>})}</tbody></table>{!rows.length&&<div className="empty">Nenhum diagnóstico corresponde aos filtros.</div>}</div>
    </section>
  </section></main>;
}

function Sidebar(){return <aside className="sidebar"><div className="side-brand"><span className="brand-mark">CB</span><span>Cristian Barbosa<strong>Consultor Financeiro</strong></span></div><nav><span>MENU</span><a className="active" href="#">▦ <b>Diagnósticos</b></a></nav><footer>Dados protegidos<br/>Acesso interno</footer></aside>}

function Detail({diagnostic:d,onBack}:{diagnostic:Diagnostic;onBack:()=>void}){
  const m=metrics(d), revenue=m.revenue, costs=d.dre_impostos+d.dre_compras+d.dre_folha+d.dre_despesas_adm+m.financial;
  const efficiency=d.funcionarios_qtd?revenue/100/d.funcionarios_qtd:0, efficiencyLevel=efficiency>=30000?"Saudável":efficiency>=15000?"Atenção":"Baixa";
  const assetCurrentPct=percent(m.currentAssets,m.totalAssets);
  const scenarios=[[-.15,"Pessimista"],[0,"Realista"],[.15,"Otimista"]].map(([variation,label])=>{const v=variation as number;const rev=revenue*(1+v);const variable=(d.dre_impostos+d.dre_compras)*(1+v);return{label:label as string,variation:v,result:rev-variable-d.dre_folha-d.dre_despesas_adm-m.financial};});
  const dreRows=[["Receita Operacional Bruta",revenue],["(−) Impostos sobre vendas",-d.dre_impostos],["Receita Líquida",m.net],["(−) Custo das mercadorias",-d.dre_compras],["Lucro Bruto",m.gross],["(−) Salários e encargos",-d.dre_folha],["(−) Gastos administrativos",-d.dre_despesas_adm],["(−) Despesas financeiras",-m.financial]] as [string,number][];
  const whatsapp=d.whatsapp.replace(/\D/g,"");
  return <main className="app-shell"><Sidebar/><section className="workspace detail"><header className="detail-top"><button className="back" onClick={onBack}>← Voltar aos diagnósticos</button><form action="/api/logout" method="post"><button className="ghost">Sair</button></form></header>
    <section className="company-hero"><div className="hero-id"><span>{initials(d.empresa_nome)}</span><div><small>Diagnóstico financeiro</small><h1>{d.empresa_nome}</h1><p>{d.atividade} · {d.cidade}</p></div></div><div className="hero-contact"><div><small>Responsável</small><strong>{d.nome}</strong><span>{d.email}</span></div><a href={`https://wa.me/55${whatsapp}`} target="_blank" rel="noreferrer">Abrir WhatsApp ↗</a></div></section>
    <div className="detail-meta"><span>Preenchido em {date(d.created_at)}</span><span>{d.funcionarios_qtd} funcionário{d.funcionarios_qtd===1?"":"s"}</span><span>{d.faturamento}</span></div>
    <section className="kpi-grid executive-grid"><article><small>Faturamento</small><strong>{money(revenue)}</strong><span>Receita operacional bruta</span></article><article><small>Resultado operacional estimado</small><strong className={m.operating>=0?"green":"red"}>{money(m.operating)}</strong><span>Após impostos, compras, folha e administrativo</span></article><article><small>Margem operacional</small><strong className={m.operating>=0?"green":"red"}>{pct(percent(m.operating,revenue))}</strong><span>Resultado sobre o faturamento</span></article><article><small>Ativo total</small><strong>{money(m.totalAssets)}</strong><span>Circulante + imobilizado</span></article><article><small>Capital de giro líquido</small><strong className={m.workingCapital>=0?"green":"red"}>{money(m.workingCapital)}</strong><span>Ativo circulante − passivo circulante</span></article><article><small>Dívida bancária total</small><strong>{money(m.bankDebt)}</strong><span>Curto + longo prazo</span></article></section>
    {m.operating<0||costs>revenue?<div className="critical"><span>!</span><div><strong>Atenção crítica</strong><p>Os custos consomem {pct(percent(costs,revenue))} da receita. A empresa está operando {m.operating<0?"no prejuízo":"com margem de risco"}.</p></div></div>:<div className="positive-note"><span>✓</span><div><strong>Operação lucrativa</strong><p>A empresa preserva {pct(percent(m.operating,revenue))} da receita como resultado operacional.</p></div></div>}
    <section className="analysis-grid"><article className="analysis-card"><div className="card-title"><div><span className="eyebrow">DRE</span><h2>Resultado do mês</h2></div><Status value={m.operating}/></div><div className="financial-table">{dreRows.map(([label,value],i)=><div className={[2,4].includes(i)?"subtotal":""} key={label}><span>{label}</span><strong className={value<0?"minus":""}>{money(value)}</strong><small>{pct(percent(Math.abs(value),revenue))}</small></div>)}<div className="total"><span>{m.operating>=0?"LUCRO OPERACIONAL":"PREJUÍZO OPERACIONAL"}</span><strong>{money(m.operating)}</strong><small>{pct(percent(m.operating,revenue))}</small></div></div></article>
      <article className="analysis-card"><div className="card-title"><div><span className="eyebrow">Balanço patrimonial</span><h2>Posição patrimonial</h2></div><span className="pl-chip">PL {money(m.equity)}</span></div><div className="asset-chart"><div className="donut" style={{background:`conic-gradient(#2f8a68 0 ${assetCurrentPct}%,#d6ad57 ${assetCurrentPct}% 100%)`}}><span>{money(m.totalAssets)}</span><small>Total ativo</small></div><div className="legend"><span><i className="circulante"/>Circulante <b>{pct(assetCurrentPct)}</b></span><span><i className="nao"/>Não-circulante <b>{pct(100-assetCurrentPct)}</b></span></div></div><div className="balance-columns"><div><h3>ATIVO</h3><p><span>Ativo circulante</span><strong>{money(m.currentAssets)}</strong></p><p><span>Imobilizado</span><strong>{money(d.ativo_imobilizado)}</strong></p><p className="sum"><span>Total do ativo</span><strong>{money(m.totalAssets)}</strong></p></div><div><h3>PASSIVO + PL</h3><p><span>Passivo circulante</span><strong>{money(m.currentLiabilities)}</strong></p><p><span>Passivo não-circulante</span><strong>{money(d.passivo_bancos_longo)}</strong></p><p><span>Patrimônio líquido</span><strong>{money(m.equity)}</strong></p><p className="sum"><span>Total passivo + PL</span><strong>{money(m.totalLiabilities+m.equity)}</strong></p></div></div><div className="closed">✓ Balanço fechado: Ativo = Passivo + PL</div></article>
    </section>
    <section className="indicators"><div className="section-heading"><span className="eyebrow">Indicadores</span><h2>Os 3 pontos vitais do negócio</h2></div><div className="indicator-grid"><article><h3>Saúde financeira</h3><p>Percentuais sobre a receita bruta.</p><Health label="Salários e encargos" value={percent(d.dre_folha,revenue)} good={20} warn={30}/><Health label="Gastos administrativos" value={percent(d.dre_despesas_adm,revenue)} good={15} warn={25}/><Health label="Despesas financeiras" value={percent(m.financial,revenue)} good={3} warn={6}/></article><article><h3>Eficiência da equipe</h3><p>Receita mensal por funcionário.</p><div className="efficiency"><strong>{money(efficiency*100)}</strong><span>/ funcionário</span></div><div className="benchmark"><span className={efficiency>=15000?"fill":""}/><span className={efficiency>=30000?"fill":""}/><span className={efficiency>=30000?"fill":""}/></div><small>Referência genérica: crítico &lt; R$ 15 mil · saudável ≥ R$ 30 mil. Ajustar por setor na devolutiva.</small></article><article><h3>Qualificação do lead</h3><p>Contexto declarado no primeiro formulário.</p><dl><dt>Controle atual</dt><dd>{d.controle}</dd><dt>Principal desafio</dt><dd>{d.desafio}</dd><dt>Como conheceu</dt><dd>{d.origem}</dd></dl></article></div></section>
    <section className="scenarios"><div className="section-heading"><span className="eyebrow">Projeções</span><h2>Cenários para o próximo mês</h2><p>Receita, impostos e compras variam em ±15%; folha, despesas administrativas e financeiras permanecem fixas.</p></div><div className="scenario-grid">{scenarios.map((s)=><article key={s.label} className={s.label==="Realista"?"featured":""}><span>{s.label}</span><small>{s.variation>0?"+":""}{pct(s.variation*100)} na receita</small><strong className={s.result>=0?"green":"red"}>{money(s.result)}</strong><em>Resultado operacional</em></article>)}</div></section>
  </section></main>;
}
