"use client";

import type { Diagnostic } from "../lib/diagnostics";
import { calculateFinancialMetrics, numeric } from "../lib/financial-metrics";

const brl = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL", minimumFractionDigits:0, maximumFractionDigits:0 });
const brl2 = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL", minimumFractionDigits:2, maximumFractionDigits:2 });
const money = (value:number|null|undefined) => value == null || !Number.isFinite(Number(value)) ? "Não disponível" : brl.format(Number(value)/100);
const reais = (value:number|null) => value == null || !Number.isFinite(value) ? "Não disponível" : brl2.format(value);
const percentage = (value:number|null, digits=1) => value == null || !Number.isFinite(value) ? "Não disponível" : `${(value*100).toFixed(digits).replace(".",",")}%`;
const multiple = (value:number|null) => value == null || !Number.isFinite(value) ? "Não disponível" : `${value.toFixed(2).replace(".",",")}×`;
const formatDate = (value:string|null|undefined) => { if(!value)return "Não disponível"; const d=new Date(value); return Number.isNaN(d.getTime())?"Não disponível":new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d); };
const initials = (name:string) => name.split(" ").slice(0,2).map((p)=>p[0]).join("").toUpperCase();

function Badge({tone,children}:{tone:"good"|"warn"|"bad"|"neutral";children:React.ReactNode}){return <span className={`metric-badge ${tone}`}>{children}</span>}
function MetricCard({label,value,description,tone}:{label:string;value:string;description:string;tone?:"good"|"bad"}){return <article><small>{label}</small><strong className={tone==="good"?"green":tone==="bad"?"red":""}>{value}</strong><span>{description}</span></article>}
function RatioCard({title,value,text,tone="neutral"}:{title:string;value:string;text:string;tone?:"good"|"warn"|"bad"|"neutral"}){return <article className="ratio-card"><div><h3>{title}</h3><Badge tone={tone}>{value}</Badge></div><p>{text}</p></article>}
function BarRow({label,value,total,color="green"}:{label:string;value:number;total:number;color?:"green"|"gold"|"red"}){const share=total>0?value/total:null;return <div className="composition-row"><div><span>{label}</span><strong>{money(value)} · {percentage(share)}</strong></div><div className="composition-track"><i className={color} style={{width:`${Math.max(0,Math.min(100,(share??0)*100))}%`}}/></div></div>}
function RawGroup({title,rows}:{title:string;rows:[string,React.ReactNode][]}){return <article className="raw-group"><h3>{title}</h3><div>{rows.map(([label,value])=><p key={label}><span>{label}</span><strong>{value}</strong></p>)}</div></article>}

function Sidebar(){return <aside className="sidebar"><div className="side-brand"><span className="brand-mark">CB</span><span>Cristian Barbosa<strong>Consultor Financeiro</strong></span></div><nav><span>MENU</span><a className="active" href="#">▦ <b>Diagnósticos</b></a></nav><footer>Dados protegidos<br/>Acesso interno</footer></aside>}

export function FinancialDetail({diagnostic:d,onBack}:{diagnostic:Diagnostic;onBack:()=>void}){
  const m=calculateFinancialMetrics(d);
  const whatsapp=(d.whatsapp||"").replace(/\D/g,"");
  const liquidityTone=m.currentLiquidity==null?"neutral":m.currentLiquidity>=1?"good":"bad";
  const capitalTone=m.workingCapital>0?"good":m.workingCapital<0?"bad":"warn";
  const resultTone=m.operatingResult>=0?"good":"bad";
  const assetCurrentShare=m.totalAssets>0?m.currentAssets/m.totalAssets:null;
  const expenseItems=[{label:"Impostos",value:m.taxes,color:"gold" as const},{label:"Compras",value:m.purchases,color:"green" as const},{label:"Folha",value:m.payroll,color:"green" as const},{label:"Administrativo",value:m.admin,color:"gold" as const}];
  const dreRows:[string,number,boolean][]=[["Receita operacional bruta",m.revenue,true],["(−) Impostos",-m.taxes,false],["Receita líquida",m.netRevenue,true],["(−) Compras / custo das mercadorias",-m.purchases,false],["Resultado bruto",m.grossResult,true],["(−) Folha",-m.payroll,false],["(−) Despesas administrativas",-m.admin,false]];
  const challengeProfit=(d.desafio||"").toLocaleLowerCase("pt-BR").includes("lucro");
  const conclusions=[
    {title:"Liquidez",tone:liquidityTone,text:m.currentLiquidity==null?"Não há base suficiente para calcular a liquidez corrente.":`Para cada R$ 1,00 em obrigações de curto prazo, a empresa possui ${brl2.format(m.currentLiquidity)} em ativos circulantes.`},
    {title:"Caixa",tone:m.immediateLiquidity==null?"neutral":m.immediateLiquidity>=1?"good":"warn",text:m.immediateLiquidity==null?"A cobertura imediata não está disponível.":`O caixa disponível cobre ${percentage(m.immediateLiquidity)} das obrigações de curto prazo.`},
    {title:"Estoques",tone:"neutral" as const,text:assetCurrentShare==null?"A participação dos estoques não está disponível.":`${percentage(m.totalAssets>0?m.inventory/m.totalAssets:null)} dos ativos da empresa estão concentrados em estoques.`},
    {title:"Endividamento",tone:m.bankDebtToRevenue==null?"neutral":m.bankDebtToRevenue<=.5?"good":"warn",text:m.bankDebtToRevenue==null?"A relação entre dívida bancária e faturamento não está disponível.":`A dívida bancária corresponde a ${percentage(m.bankDebtToRevenue)} do faturamento informado.`},
    {title:"Rentabilidade",tone:resultTone,text:m.operatingMargin==null?"A margem operacional não está disponível.":`A operação gera aproximadamente ${reais(m.operatingMargin*100)} de resultado para cada R$ 100 faturados.`},
    {title:"Estrutura de custos",tone:m.purchaseWeight!=null&&m.purchaseWeight>.5?"warn":"neutral" as const,text:m.purchaseWeight==null?"O peso das compras não está disponível.":`Compras representam ${percentage(m.purchaseWeight)} do faturamento e são ${m.purchases>=Math.max(m.payroll,m.admin,m.taxes)?"o principal componente":"um componente relevante"} da estrutura de custos.`},
  ];

  return <main className="app-shell"><Sidebar/><section className="workspace detail premium-report">
    <header className="detail-top"><button className="back" onClick={onBack}>← Voltar aos diagnósticos</button><form action="/api/logout" method="post"><button className="ghost">Sair</button></form></header>
    <section className="company-hero"><div className="hero-id"><span>{initials(d.empresa_nome||"Empresa")}</span><div><small>Raio-X financeiro</small><h1>{d.empresa_nome||"Empresa não informada"}</h1><p>{d.atividade||"Atividade não informada"} · {d.cidade||"Cidade não informada"}</p></div></div><div className="hero-contact"><div><small>Responsável</small><strong>{d.nome||"Não informado"}</strong><span>{d.email||"E-mail não informado"}</span></div>{whatsapp&&<a href={`https://wa.me/55${whatsapp}`} target="_blank" rel="noreferrer">Abrir WhatsApp ↗</a>}</div></section>
    <div className="detail-meta"><span>Preenchido em {formatDate(d.created_at)}</span><span>{numeric(d.funcionarios_qtd)} funcionário{numeric(d.funcionarios_qtd)===1?"":"s"}</span><span>{d.faturamento||"Faixa não informada"}</span></div>

    <section className="kpi-grid executive-grid"><MetricCard label="Faturamento" value={money(d.dre_faturamento)} description="Receita operacional bruta"/><MetricCard label="Resultado operacional estimado" value={money(m.operatingResult)} description="Após impostos, compras, folha e administrativo" tone={m.operatingResult>=0?"good":"bad"}/><MetricCard label="Margem operacional" value={percentage(m.operatingMargin)} description="Resultado sobre o faturamento" tone={m.operatingResult>=0?"good":"bad"}/><MetricCard label="Ativo total" value={money(m.totalAssets)} description="Ativo circulante + imobilizado"/><MetricCard label="Capital de giro líquido" value={money(m.workingCapital)} description="Ativo circulante − passivo circulante" tone={m.workingCapital>=0?"good":"bad"}/><MetricCard label="Dívida bancária total" value={money(m.bankDebt)} description="Bancos no curto + longo prazo"/></section>

    <div className={m.operatingResult>=0?"positive-note diagnostic-highlight":"critical diagnostic-highlight"}><span>{m.operatingResult>=0?"✓":"!"}</span><div><strong>Destaque do diagnóstico</strong><p>{m.operatingMargin==null?"Não há faturamento suficiente para calcular a margem operacional.":`Com os dados informados, o resultado operacional estimado é ${money(m.operatingResult)}, equivalente a ${percentage(m.operatingMargin)} do faturamento.`}</p></div></div>

    <section className="analysis-grid report-section"><article className="analysis-card"><div className="card-title"><div><span className="eyebrow">DRE</span><h2>Resultado operacional estimado</h2></div><Badge tone={resultTone}>{percentage(m.operatingMargin)}</Badge></div><div className="financial-table">{dreRows.map(([label,value,subtotal])=><div className={subtotal?"subtotal":""} key={label}><span>{label}</span><strong className={value<0?"minus":""}>{money(value)}</strong><small>{percentage(m.revenue>0?Math.abs(value)/m.revenue:null)}</small></div>)}<div className="total"><span>RESULTADO OPERACIONAL ESTIMADO</span><strong>{money(m.operatingResult)}</strong><small>{percentage(m.operatingMargin)}</small></div></div></article>
      <article className="analysis-card"><div className="card-title"><div><span className="eyebrow">Balanço patrimonial</span><h2>Posição patrimonial atual</h2></div><span className="pl-chip">PL {money(m.equity)}</span></div><div className="asset-chart"><div className="donut" style={{background:`conic-gradient(#163a63 0 ${(assetCurrentShare??0)*100}%,#d2ae4a ${(assetCurrentShare??0)*100}% 100%)`}}><span>{money(m.totalAssets)}</span><small>Total ativo</small></div><div className="legend"><span><i className="circulante"/>Circulante <b>{percentage(assetCurrentShare)}</b></span><span><i className="nao"/>Não-circulante <b>{percentage(assetCurrentShare==null?null:1-assetCurrentShare)}</b></span></div></div><div className="balance-columns"><div><h3>ATIVO</h3><p><span>Ativo circulante</span><strong>{money(m.currentAssets)}</strong></p><p><span>Imobilizado</span><strong>{money(m.fixedAssets)}</strong></p><p className="sum"><span>Total do ativo</span><strong>{money(m.totalAssets)}</strong></p></div><div><h3>PASSIVO + PL</h3><p><span>Passivo circulante</span><strong>{money(m.currentLiabilities)}</strong></p><p><span>Passivo não-circulante</span><strong>{money(m.bankLong)}</strong></p><p><span>Patrimônio líquido</span><strong>{money(m.equity)}</strong></p><p className="sum"><span>Total passivo + PL</span><strong>{money(m.totalLiabilities+m.equity)}</strong></p></div></div><div className="closed">✓ Balanço fechado: Ativo = Passivo + PL</div></article></section>

    <section className="report-section"><div className="section-heading"><span className="eyebrow">Saúde financeira</span><h2>Capacidade de cumprir obrigações</h2><p>Leitura da liquidez e do capital de giro com base na fotografia atual.</p></div><div className="ratio-grid"><RatioCard title="Liquidez corrente" value={multiple(m.currentLiquidity)} tone={liquidityTone} text={m.currentLiquidity==null?"Não disponível: não há passivo circulante para comparação.":`Para cada R$ 1,00 de obrigação de curto prazo, há ${brl2.format(m.currentLiquidity)} em ativos circulantes.`}/><RatioCard title="Liquidez seca" value={multiple(m.dryLiquidity)} tone={m.dryLiquidity==null?"neutral":m.dryLiquidity>=1?"good":"warn"} text={m.dryLiquidity==null?"Não disponível.":`Sem considerar estoques, há ${brl2.format(m.dryLiquidity)} para cada R$ 1,00 de obrigação de curto prazo.`}/><RatioCard title="Liquidez imediata" value={percentage(m.immediateLiquidity)} tone={m.immediateLiquidity==null?"neutral":m.immediateLiquidity>=1?"good":"warn"} text={m.immediateLiquidity==null?"Não disponível.":`O caixa disponível cobre ${percentage(m.immediateLiquidity)} das obrigações de curto prazo.`}/><RatioCard title="Capital de giro" value={money(m.workingCapital)} tone={capitalTone} text={m.workingCapital>0?"Positivo: os ativos circulantes superam as obrigações de curto prazo.":m.workingCapital<0?"Negativo: as obrigações de curto prazo superam os ativos circulantes.":"Em equilíbrio: ativo e passivo circulantes possuem o mesmo valor."}/></div></section>

    <section className="report-section debt-section"><div className="section-heading"><span className="eyebrow">Estrutura de endividamento</span><h2>Como as obrigações estão distribuídas</h2><p>Capital social não é considerado dívida operacional.</p></div><div className="debt-layout"><div className="ratio-grid debt-metrics"><RatioCard title="Endividamento sobre ativos" value={percentage(m.debtToAssets)} text="Total das obrigações operacionais em relação ao ativo total."/><RatioCard title="Dívida bancária / faturamento" value={percentage(m.bankDebtToRevenue)} text="Dívidas com bancos comparadas ao faturamento informado."/><RatioCard title="Bancos — curto prazo" value={percentage(m.bankShortShare)} text="Participação do curto prazo na dívida bancária total."/><RatioCard title="Bancos — longo prazo" value={percentage(m.bankLongShare)} text="Participação do longo prazo na dívida bancária total."/></div><article className="analysis-card composition-card"><h3>Composição das obrigações</h3><BarRow label="Fornecedores" value={m.suppliers} total={m.totalLiabilities}/><BarRow label="Bancos curto prazo" value={m.bankShort} total={m.totalLiabilities} color="gold"/><BarRow label="Bancos longo prazo" value={m.bankLong} total={m.totalLiabilities} color="gold"/><BarRow label="Impostos atrasados" value={m.overdueTaxes} total={m.totalLiabilities} color="red"/><BarRow label="Outras obrigações" value={m.otherLiabilities} total={m.totalLiabilities}/></article></div></section>

    <section className="report-section hundred-section"><div className="section-heading"><span className="eyebrow">Leitura simples</span><h2>Para cada R$ 100 faturados</h2><p>Quanto do faturamento é destinado a cada parte da operação.</p></div>{m.revenue>0?<><div className="hundred-bar">{expenseItems.map((item)=><i key={item.label} className={item.color} style={{width:`${Math.max(0,(item.value/m.revenue)*100)}%`}}/>)}<i className={m.operatingResult>=0?"result-positive":"result-negative"} style={{width:`${Math.max(0,Math.abs(m.operatingResult/m.revenue)*100)}%`}}/></div><div className="hundred-grid">{expenseItems.map((item)=><article key={item.label}><span>{item.label}</span><strong>{reais(item.value/m.revenue*100)}</strong></article>)}<article><span>Resultado operacional</span><strong className={m.operatingResult>=0?"green":"red"}>{reais(m.operatingResult/m.revenue*100)}</strong></article></div></>:<div className="unavailable">Não disponível: o faturamento informado é zero ou está ausente.</div>}</section>

    <section className="report-section"><div className="section-heading"><span className="eyebrow">Composição do ativo</span><h2>Onde está o dinheiro da empresa?</h2><p>Distribuição dos recursos informados no diagnóstico.</p></div><article className="analysis-card composition-card asset-composition"><BarRow label="Caixa e bancos" value={m.cash} total={m.totalAssets}/><BarRow label="Contas a receber" value={m.receivables} total={m.totalAssets}/><BarRow label="Estoques" value={m.inventory} total={m.totalAssets} color="gold"/><BarRow label="Outros valores a receber" value={m.otherReceivables} total={m.totalAssets}/><BarRow label="Imobilizado" value={m.fixedAssets} total={m.totalAssets} color="gold"/></article></section>

    <section className="report-section"><div className="section-heading"><span className="eyebrow">Eficiência operacional</span><h2>Indicadores da estrutura atual</h2><p>Relações matemáticas, sem benchmark setorial ou classificação arbitrária.</p></div><div className="operational-grid"><MetricCard label="Faturamento por funcionário" value={m.revenuePerEmployee==null?"Não disponível":money(m.revenuePerEmployee)} description="Receita ÷ quantidade de funcionários"/><MetricCard label="Resultado por funcionário" value={m.resultPerEmployee==null?"Não disponível":money(m.resultPerEmployee)} description="Resultado operacional ÷ funcionários" tone={m.resultPerEmployee!=null&&m.resultPerEmployee<0?"bad":undefined}/><MetricCard label="Folha por funcionário" value={m.payrollPerEmployee==null?"Não disponível":money(m.payrollPerEmployee)} description="Folha ÷ quantidade de funcionários"/><MetricCard label="Peso da folha" value={percentage(m.payrollWeight)} description="Folha sobre o faturamento"/><MetricCard label="Peso administrativo" value={percentage(m.adminWeight)} description="Despesas administrativas sobre receita"/><MetricCard label="Peso de impostos" value={percentage(m.taxWeight)} description="Impostos sobre o faturamento"/><MetricCard label="Peso das compras" value={percentage(m.purchaseWeight)} description="Compras sobre o faturamento"/></div></section>

    <section className="report-section"><div className="section-heading"><span className="eyebrow">Diagnóstico automático</span><h2>Principais conclusões</h2><p>Insights objetivos gerados exclusivamente a partir dos dados informados.</p></div><div className="conclusions-grid">{conclusions.map((item)=><article className={`conclusion ${item.tone}`} key={item.title}><span>{item.tone==="good"?"✓":item.tone==="bad"?"!":"•"}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></section>

    <section className="report-section context-section"><div className="section-heading"><span className="eyebrow">Contexto do cliente</span><h2>O que motivou o diagnóstico</h2></div><div className="context-grid"><article><small>Controle financeiro atual</small><strong>{d.controle||"Não informado"}</strong></article><article><small>Principal desafio</small><strong>{d.desafio||"Não informado"}</strong>{challengeProfit&&<p>Com os dados informados, o resultado estimado é {money(m.operatingResult)} ({percentage(m.operatingMargin)} do faturamento).</p>}</article><article><small>Origem</small><strong>{d.origem||"Não informada"}</strong></article></div></section>

    <section className="report-section raw-section"><div className="section-heading"><span className="eyebrow">Conferência</span><h2>Dados informados</h2><p>Valores informados pelo cliente no momento do preenchimento do diagnóstico.</p></div><div className="raw-grid"><RawGroup title="Ativos" rows={[["Caixa e bancos",money(d.ativo_caixa_bancos)],["Contas a receber",money(d.ativo_contas_receber)],["Estoques",money(d.ativo_estoques)],["Outros a receber",money(d.ativo_outros_receber)],["Imobilizado",money(d.ativo_imobilizado)]]}/><RawGroup title="Passivos" rows={[["Fornecedores",money(d.passivo_fornecedores)],["Bancos curto prazo",money(d.passivo_bancos_curto)],["Impostos",money(d.passivo_impostos)],["Outras obrigações",money(d.passivo_outras_obrigacoes)],["Capital social",money(d.passivo_capital_social)],["Bancos longo prazo",money(d.passivo_bancos_longo)]]}/><RawGroup title="Resultado / DRE" rows={[["Faturamento",money(d.dre_faturamento)],["Impostos",money(d.dre_impostos)],["Compras",money(d.dre_compras)],["Folha",money(d.dre_folha)],["Despesas administrativas",money(d.dre_despesas_adm)]]}/><RawGroup title="Dados da empresa" rows={[["ID",String(d.id??"Não informado")],["Empresa",d.empresa_nome||"Não informada"],["CNPJ",d.cnpj||"Não informado"],["Atividade",d.atividade||"Não informada"],["Funcionários",String(d.funcionarios_qtd??"Não informado")],["Faixa de funcionários",d.funcionarios||"Não informada"],["Cidade",d.cidade||"Não informada"],["Responsável",d.nome||"Não informado"],["WhatsApp",d.whatsapp||"Não informado"],["E-mail",d.email||"Não informado"],["Faixa de faturamento",d.faturamento||"Não informada"],["Controle",d.controle||"Não informado"],["Desafio",d.desafio||"Não informado"],["Origem",d.origem||"Não informada"],["Status",d.status||"Não informado"],["Criado em",formatDate(d.created_at)],["Atualizado em",formatDate(d.updated_at)]]}/></div></section>
  </section></main>;
}
